/* This file was generated by mongo-type-gen */

import { gql } from 'graphql-tag';

export default gql`

type UserDocAddress {
  city: String!
  state: String!
  street: String!
  zip: String!
}

type UserDocChildren {
  _id: ObjectId!
  age: Int!
  createdAt: Date!
  name: String!
  updatedAt: Date
}

enum UserDocGenderEnum {
  MALE
  FEMALE
}

type UserDoc {
  _id: ObjectId!
  address: UserDocAddress!
  age: Int
  children: [UserDocChildren]
  name: String!
}

`