/* This file was generated by mongo-type-gen */

import { ObjectId } from 'mongodb';

export type UserDocAddress = {
  city: string;
  state: string;
  street: string;
  zip: string;
};

export type UserDocChildren = {
  _id: ObjectId;
  age: number | null;
  createdAt: Date;
  name: string;
  updatedAt?: Date;
};

export enum UserDocGenderEnum {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export type UserDoc = {
  _id: ObjectId;
  address: UserDocAddress;
  age?: number | null;
  children?: UserDocChildren[];
  name: string;
};