/* This file is generated by mongo-type-gen.  Do not edit */

import { gql } from 'graphql-tag';

export default gql`

  type StudentDoc {
    gpa: Float
    name: String!
    year: Int!
  }

  type UserDocAddressChildren {
    _id: ObjectId!
    age: Int!
    createdAt: Date!
    name: String!
    updatedAt: Date
  }

  type UserDocAddress {
    children: [UserDocAddressChildren]
    city: String!
    state: String!
    street: String!
    zip: String!
  }

  type UserDocChildrenSiblings {
    _id: ObjectId!
    age: Int!
    createdAt: Date!
    name: String!
    updatedAt: Date
  }

  type UserDocChildren {
    _id: ObjectId!
    age: Int!
    createdAt: Date!
    name: String!
    siblings: [UserDocChildrenSiblings]
  }

   enum UserDocGenderEnum {
    FEMALE
    MALE
    UNKNOWN
  }

  type UserDoc {
    _id: ObjectId!
    address: UserDocAddress!
    age: Int
    children: [UserDocChildren]
    name: String!
    roles: [String]
  }

`;