/* This file was generated by mongo-type-gen.  Do not edit */

import { ObjectId } from 'mongodb';

export type StudentDoc = {
  gpa?: number;
  name: string;
  year: number;
};

export type UserDocAddress = {
  city: string;
  state: string;
  street: string;
  zip: string;
};

export type UserDocChildren = {
  _id: ObjectId | string;
  age: number | null;
  createdAt: Date;
  name: string;
  updatedAt?: Date;
};

export enum UserDocGenderEnum {
  FEMALE = 'FEMALE',
  MALE = 'MALE',
  UNKNOWN = 'UNKNOWN',
}

export type UserDoc = {
  _id: ObjectId | string;
  address: UserDocAddress;
  age?: number | null;
  children?: UserDocChildren[];
  name: string;
  roles?: string[];
};