//import fs from 'fs';
import { MongoClient } from 'mongodb';

import formatJsonString from './common/formatJsonSting';
import getConfig from './common/getConfig';
import writeFileAsync from './common/writeFileAsync';
import pkg from '../package.json';

// Replace the uri string with your MongoDB deployment's connection string.
let client: MongoClient;

async function genValidators(): Promise<void> {
  try {
    const config = await getConfig();
    const files = [];
    const banner = '/* This file is generated by mongo-type-gen.  Do not edit */';

    client = new MongoClient(config.uri);

    const db = client.db(config.db);
    const listCollections = await db.listCollections().toArray();

    for (const col of listCollections) {
      const c = col as unknown as { options: { validator: string } };
      const v = c.options.validator;
      const s = formatJsonString(v);

      const tsCode = [banner, `export default ${s};`].join('\n\n');
      const file = writeFileAsync(`./${config.output}/${col.name}.validator.ts`, tsCode);
      files.push(file);
    }

    await Promise.all(files);
    console.info(`✅ ${pkg.name} validators generated!`);
  } finally {
    await client.close();
  }
}
genValidators().catch(console.error);
