import formatJsonString from './common/formatJsonSting';
import writeFile from './common/writeFile';
import MtgCollection from './types/MtgCollection';
import pkg from '../package.json';

const banner = '/* This file is generated by mongo-type-gen.  Do not edit */';

async function writeCollectionFiles({
  collections,
  dir,
}: {
  collections: MtgCollection[];
  dir: string;
}): Promise<void> {
  try {
    await Promise.all(
      collections.map(async (c) => {
        const str = formatJsonString(c);
        const tsCode = [banner, `export default ${str};`].join('\n\n');
        await writeFile({ data: tsCode, dir, file: `${c.name}.collection.ts` });
      }),
    );
    console.info(`✅ ${pkg.name} collections downloaded from Mongo!`);
  } catch (e) {
    const error = e instanceof Error ? e.message : e;
    console.error(`❌ ${pkg.name} failed to download validators from Mongo: `, error);
  }
}

export default writeCollectionFiles;
