import formatJsonString from './formatJsonSting';
import writeFile from './writeFile';
import pkg from '../../package.json';
import MtgCollection from '../types/MtgCollection';

const banner = '/* This file is generated by mongo-type-gen.  Do not edit */';

async function writeCollectionFiles({
  collections,
  dir,
}: {
  collections: MtgCollection[];
  dir: string;
}): Promise<void> {
  try {
    await Promise.all(
      collections.map(async (c) => {
        const str = formatJsonString(c);
        const tsCode = [banner, `export default ${str};`].join('\n\n');
        await writeFile({ data: tsCode, dir, file: `${c.name}.collection.js` });
      }),
    );
  } catch (e) {
    const error = e instanceof Error ? JSON.stringify(e, Object.getOwnPropertyNames(e)) : JSON.stringify(e);
    console.error(`❌ ${pkg.name} failed to download validators from Mongo: `, error);
  }
}

export default writeCollectionFiles;
