/* This file is generated by mongo-type-gen.  Do not edit this file.  Edit the $jsonSchema in in **.collection.ts. */

import { gql } from 'graphql-tag';

export default gql`

  scalar JSONObject

  enum CollectionEnum {
    students
    users
  }

  type StudentDoc {
    gpa: Float
    name: String!
    test4: String
    year: Int!
  }

  type UserDocAddressChildren {
    _id: ObjectId!
    age: Int!
    createdAt: Date!
    name: String!
    updatedAt: Date
  }

  type UserDocAddress {
    children: [UserDocAddressChildren]
    city: String!
    state: String!
    street: String!
    zip: String!
  }

  type UserDocChildrenSibling {
    _id: ObjectId!
    age: Int!
    createdAt: Date!
    name: String!
    updatedAt: Date
  }

  type UserDocChildren {
    _id: ObjectId!
    age: Int!
    createdAt: Date!
    name: String!
    siblings: [UserDocChildrenSibling]
  }

   enum UserDocGenderEnum {
    FEMALE
    MALE
    UNKNOWN
  }

  type UserDoc {
    _id: ObjectId!
    address: UserDocAddress!
    age: Int
    children: [UserDocChildren]
    gender: UserDocGenderEnum
    name: String!
    roles: [String]
    testObj: JSONObject
  }

`;