name: pr

on:
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - run: |
          set -xe
          npm ci --force
          npm run checks:ci
