name: pr

on:
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: 'package.json'
      - run: |
          set -xe
          npm ci
          npm run checks:ci
