name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          registry-url: 'https://registry.npmjs.org'

      - name: Run Checks and Build
        run: |
          set -xe
          npm ci
          npm run checks:ci
          npm run build

      - name: Set package.json version to release
        run: |
          set -xe
          tag="${{ github.event.release.tag_name }}"
          version="${tag#v}"
          echo "version is set to $version"
          sed -i "s/\"version\": \".*\"/\"version\": \"$version\"/" package.json
          echo "package.json updated"
          cat package.json

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm publish
